display_name="Bowser's Big Blast: A Bowser Micromoveset"
description="""
Brings the P+ Fireball to Ult, as well as Melee Nair and a new Dash Attack animation
"""
version="1.0"
category="Param"
authors="C#"